"""empty message

Revision ID: 2182d5df4645
Revises: 272572932b71
Create Date: 2021-06-03 14:26:44.971354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2182d5df4645'
down_revision = '272572932b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistid', sa.Integer(), nullable=False),
    sa.Column('venueid', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venueid'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
